# API Keys
XAI_API_KEY = "xai-JDGZAFIQIaBUNgkEImOwF7GRYxLbpXzJVlxemUmtzFeLnOi1KVOBG0M4EgnZLpGrNFkbANI6DUZG2F8S"
NEWS_API_KEY = "48446589765e41a2afd2b60242e59979"
ALPHA_VANTAGE_API_KEY = "HUH7ZLAD3KP3H3LI" 